const Country = {
	Afghanistan: {},
	Albania: {se: "Albanien"},
	Algeria: {se: "Algeriet"},
	Andorra: {},
	Angola: {},
	AntiguaAndBarbuda: {se: "Antigua och Barbuda"},
	Argentina: {},
	Armenia: {se: "Armenien"},
	Australia: {se: "Australien"},
	Austria: {se: "Österrike"},
	Azerbaijan: {se: "Azerbajdzjan"},
	Bahamas: {},
	Bahrain: {},
	Bangladesh: {},
	Barbados: {},
	Belarus: {alt: "Vitryssland"},
	Belgium: {se: "Belgien"},
	Belize: {},
	Benin: {},
	Bhutan: {},
	Bolivia: {},
	BosniaAndHerzegovina: {se: "Bosnien och Hercegovina"},
	Botswana: {},
	Brazil: {se: "Brasilien"},
	Brunei: {},
	Bulgaria: {se: "Bulgarien"},
	BurkinaFaso: {se: "Burkina Faso"},
	Burundi: {},
	CaboVerde: {se: "Kap Verde"},
	Cambodia: {se: "Kambodja"},
	Cameroon: {se: "Kamerun"},
	Canada: {se: "Kanada"},
	CentralAfricanRepublic: {se: "Centralafrikanska republiken"},
	Chad: {se: "Tchad"},
	Chile: {},
	China: {se: "Kina"},
	Colombia: {},
	Comoros: {se: "Komorerna", alt: "Comorerna"},
	DemocraticRepublicOfTheCongo: {se: "Demokratiska republiken Kongo", alt: "Kongo-Kinshasa"},
	RepublicOfTheCongo: {se: "Republiken Kongo", alt: "Kongo-Brazzaville"},
	CostaRica: {se: "Costa Rica"},
	IvoryCoast: {se: "Elfenbenskusten"},
	Croatia: {se: "Kroatien"},
	Cuba: {se: "Kuba"},
	Cyprus: {se: "Cypern"},
	CzechRepublic: {se: "Tjeckien"},
	Denmark: {se: "Danmark"},
	Djibouti: {},
	Dominica: {},
	DominicanRepublic: {se: "Dominikanska republiken"},
	EastTimor: {se: "Östtimor", alt: "Timor-Leste"},
	Ecuador: {},
	Egypt: {se: "Egypten"},
	ElSalvador: {se: "El Salvador"},
	EquatorialGuinea: {se: "Ekvatorialguinea"},
	Eritrea: {},
	Estonia: {se: "Estland"},
	Eswatini: {alt: "Swaziland"},
	Ethiopia: {se: "Etiopien"},
	Fiji: {},
	Finland: {},
	France: {se: "Frankrike"},
	Gabon: {},
	Gambia: {},
	Georgia: {se: "Georgien"},
	Germany: {se: "Tyskland"},
	Ghana: {},
	Greece: {se: "Grekland"},
	Greenland: {se: "Grönland"},
	Grenada: {},
	Guatemala: {},
	Guam: {},
	Guinea: {},
	GuineaBissau: {se: "Guinea-Bissau"},
	Guyana: {},
	Haiti: {},
	Honduras: {},
	Hungary: {se: "Ungern"},
	Iceland: {se: "Island"},
	India: {se: "Indien"},
	Indonesia: {se: "Indonesien"},
	Iran: {},
	Iraq: {se: "Irak"},
	Ireland: {se: "Irland"},
	Israel: {},
	Italy: {se: "Italien"},
	Jamaica: {},
	Japan: {},
	Jordan: {se: "Jordanien"},
	Kazakhstan: {se: "Kazakstan"},
	Kenya: {},
	Kiribati: {},
	NorthKorea: {se: "Nordkorea"},
	SouthKorea: {se: "Sydkorea"},
	Kosovo: {},
	Kuwait: {},
	Kyrgyzstan: {se: "Kirgizistan"},
	Laos: {},
	Latvia: {se: "Lettland"},
	Lebanon: {se: "Libanon"},
	Lesotho: {},
	Liberia: {},
	Libya: {se: "Libyen"},
	Liechtenstein: {},
	Lithuania: {se: "Litauen"},
	Luxembourg: {se: "Luxemburg"},
	Madagascar: {se: "Madagaskar"},
	Malawi: {},
	Malaysia: {},
	Maldives: {se: "Maldiverna"},
	Mali: {},
	Malta: {},
	MarshallIslands: {se: "Marshallöarna"},
	Mauritania: {se: "Mauretanien"},
	Mauritius: {se: "Mauritius"},
	Mexico: {se: "Mexiko"},
	FederatedStatesOfMicronesia: {se: "Mikronesiska federationen"},
	Moldova: {se: "Moldavien"},
	Monaco: {},
	Mongolia: {se: "Mongoliet"},
	Montenegro: {},
	Morocco: {se: "Marocko"},
	Mozambique: {se: "Moçambique"},
	Myanmar: {alt: "Burma"},
	Namibia: {},
	Nauru: {},
	Nepal: {},
	Netherlands: {se: "Nederländerna"},
	NewZealand: {se: "Nya Zeeland"},
	Nicaragua: {},
	Niger: {},
	Nigeria: {},
	Niue: {},
	NorthMacedonia: {se: "Nordmakedonien", alt: "Makedonien"},
	NorthMarianaIslands: {se: "Norra Marianerna"},
	SouthMarianaIslands: {se: "Södra Marianerna"},
	Norway: {se: "Norge"},
	Oman: {},
	Pakistan: {},
	Palau: {},
	Panama: {},
	PapuaNewGuinea: {se: "Papua Nya Guinea"},
	Paraguay: {},
	Peru: {},
	Philippines: {se: "Filippinerna"},
	Poland: {se: "Polen"},
	Portugal: {},
	Qatar: {alt: "Katar"},
	Romania: {se: "Rumänien"},
	Russia: {se: "Ryssland"},
	Rwanda: {},
	SaintKittsAndNevis: {se: "Saint Kitts och Nevis"},
	SaintLucia: {se: "Saint Lucia"},
	SaintVincentAndTheGrenadines: {se: "Saint Vincent och Grenadinerna"},
	Samoa: {},
	SanMarino: {se: "San Marino"},
	SaoTomeAndPrincipe: {se: "São Tomé och Príncipe"},
	SaudiArabia: {se: "Saudiarabien"},
	Senegal: {},
	Serbia: {se: "Serbien"},
	Seychelles: {se: "Seychellerna"},
	SierraLeone: {se: "Sierra Leone"},
	Singapore: {},
	Slovakia: {},
	Slovenia: {},
	SolomonIslands: {se: "Salomonöarna"},
	Somalia: {},
	SouthAfrica: {se: "Sydafrika"},
	Spain: {se: "Spanien"},
	SriLanka: {se: "Sri Lanka"},
	Sudan: {se: "Sudan", alt: "Nordsudan"},
	SouthSudan: {se: "Sydsudan"},
	Suriname: {se: "Surinam"},
	Sweden: {se: "Sverige"},
	Switzerland: {se: "Schweiz"},
	Syria: {se: "Syrien"},
	Taiwan: {},
	Tajikistan: {se: "Tadzjikistan"},
	Tanzania: {},
	Thailand: {},
	Togo: {},
	Tonga: {},
	TrinidadAndTobago: {se: "Trinidad och Tobago"},
	Tunisia: {se: "Tunisien"},
	Turkey: {se: "Turkiet"},
	Turkmenistan: {},
	Tuvalu: {},
	Uganda: {},
	Ukraine: {se: "Ukraina"},
	UnitedArabEmirates: {se: "Förenade Arabemiraten"},
	UnitedKingdom: {se: "Storbritannien", alt: "England"},
	UnitedStates: {se: "Förenta staterna", alt: "USA"},
	Uruguay: {},
	Uzbekistan: {},
	Vanuatu: {},
	VaticanCity: {se: "Vatikanstaten"},
	Venezuela: {},
	Vietnam: {},
	WesternSahara: {se: "Västsahara"},
	Yemen: {alt: "Jemen"},
	Zambia: {},
	Zimbabwe: {}
};